name: delivery_app
description: "برنامه مدیریت تحویل بار"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  
  shared_preferences: ^2.2.2
  mobile_scanner: ^5.0.0
  connectivity_plus: ^6.0.0
  http: ^1.1.0
  excel: ^4.0.0
  pdf: ^3.10.0
  printing: ^5.11.0
  path_provider: ^2.1.0
  share_plus: ^7.0.0
  file_picker: ^6.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Vazir
  #     fonts:
  #       - asset: assets/fonts/Vazir.ttf  # اگر فونت دارید
